package map;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class Homepage extends JPanel {
    private JComboBox cmbMap;
    private JPanel pnlMain;
    private JPanel pnlImage;
    private BufferedImage bufferedImage = null;



    public Homepage() {
        final String dir = System.getProperty("user.dir");
        File file = new File(dir + "\\main.png");

        JPanel canvas;
        JFrame combobox;
        try {
            bufferedImage = ImageIO.read(file);
        } catch (IOException ex) {
            throw new RuntimeException(ex);
        }

        canvas = new JPanel() {
            private static final long serialVersionUID = 1L;

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(bufferedImage, 0, 0, null);
            }
        };

        canvas.setLayout(null);
        JButton btn1 = new JButton(new ImageIcon(dir + "\\pin.png"));
        btn1.setBounds(1860, 1650, 32, 32);
        btn1.setOpaque(false);
        btn1.setContentAreaFilled(false);
        btn1.setBorderPainted(false);

        canvas.add(btn1);
        canvas.setPreferredSize(new Dimension(bufferedImage.getWidth(), bufferedImage.getHeight()));
        JScrollPane sp = new JScrollPane(canvas);
        setLayout(new BorderLayout());
        add(sp, BorderLayout.CENTER);

        cmbMap=new JComboBox();
        String building[]={"Select Building", "Middlesex College"};
        JComboBox cb=new JComboBox(building);
        cb.setBounds(0, 0,200,20);
        cmbMap.add(cb);
        cmbMap.setLayout(null);
        cmbMap.setSize(200,20);
        cmbMap.setVisible(true);

        canvas.add(cmbMap);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pnlMain = new JPanel();
        pnlMain.setLayout(new BorderLayout(0, 0));
        cmbMap = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        cmbMap.setModel(defaultComboBoxModel1);
        pnlMain.add(cmbMap, BorderLayout.NORTH);
        final JScrollPane scrollPane1 = new JScrollPane();
        pnlMain.add(scrollPane1, BorderLayout.CENTER);
        pnlImage = new JPanel();
        pnlImage.setLayout(new BorderLayout(0, 0));
        scrollPane1.setViewportView(pnlImage);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
